// src/views/License.vue
<script setup lang="ts">
import { useTitle } from "@vueuse/core";

import NavigationBar from "../components/NavigationBar.vue";
import MainLayout from "../components/MainLayout.vue";
import PageHeader from "../components/PageHeader.vue";

useTitle("License | H. Kamran");
</script>

<template>
    <navigation-bar />

    <main-layout>
        <page-header
            header="License"
            subheader="Last Updated: January 31, 2022"
        />

        <div class="mt-7 max-w-5xl mx-auto prose prose-pink dark:prose-light">
            <ul>
                <li>
                    You may copy and distribute the content on this site, so
                    long as you credit me and I give you permission in writing
                </li>
                <li>
                    You may use the content on this site for both commercial and
                    noncommerical purposes, provided you credit me and I give
                    you permission in writing
                </li>
                <li>
                    You <strong>may not</strong> redistribute or sell the
                    content on this site, without permission in writing from me
                </li>
                <li>
                    You <strong>may not</strong> use any of the content on this
                    site to create misleading associations with products and
                    services, without permission in writing from me
                </li>
            </ul>
        </div>
    </main-layout>
</template>

// pages/legal/license.tsx
import Breadcrumbs from "../../components/Breadcrumbs";
import Head from "next/head";
import Layout from "../../components/Layout";
import type { NextPage } from "next";

const License: NextPage = () => {
    return (
        <Layout>
            <Head>
                <title>License | H. Kamran</title>
            </Head>

            <div className="mx-auto max-w-2xl">
                <Breadcrumbs
                    basePath="/"
                    baseLabel="Legal"
                    currentLabel="Privacy Policy"
                />

                <div className="space-y-2">
                    <h1 className="text-4xl font-semibold text-center mx-auto md:text-left">
                        License
                    </h1>
                    <h2 className="font-light text-xl sm:text-2xl text-center sm:text-left leading-snug text-gray-300">
                        Last Updated: April 7, 2022
                    </h2>
                </div>

                <div className="mt-6 max-w-none prose prose-invert">
                    <ul>
                        <li>
                            You may copy and distribute the content on this
                            site, so long as you credit me and I give you
                            permission in writing
                        </li>
                        <li>
                            You may use the content on this site for both
                            commercial and noncommerical purposes, provided you
                            credit me and I give you permission in writing
                        </li>
                        <li>
                            You <strong>may not</strong> redistribute or sell
                            the content on this site, without permission in
                            writing from me
                        </li>
                        <li>
                            You <strong>may not</strong> use any of the content
                            on this site to create misleading associations with
                            products and services, without permission in writing
                            from me
                        </li>
                    </ul>

                    <p>
                        I reserve the right to change the above terms at any
                        time without prior notification.
                    </p>
                </div>
            </div>
        </Layout>
    );
};

export default License;
