// src/components/NoteCard.vue
<script setup lang="ts">
const props = defineProps<{
    slug: string;
    title: string;
    description: string;
    publishDate: string;
}>();
</script>

<template>
    <div class="mt-1 pt-5">
        <div class="items-center">
            <div class="col-span-2">
                <p class="text-sm text-gray-500 dark:text-gray-400">
                    <time
                        :datetime="props.publishDate"
                        v-text="
                            new Date(
                                `${props.publishDate}T12:00:00-07:00`
                            ).toLocaleDateString(undefined, {
                                year: 'numeric',
                                month: 'long',
                                day: 'numeric',
                            })
                        "
                    />
                </p>

                <router-link
                    :to="`/notes/note/${props.slug}`"
                    class="mt-2 block"
                >
                    <p
                        class="text-xl font-semibold text-gray-800 dark:text-gray-200"
                        v-text="props.title"
                    />
                    <p
                        class="mt-2 text-base text-gray-500 dark:text-gray-400"
                        v-text="props.description"
                    />
                </router-link>

                <div class="mt-3">
                    <router-link
                        :to="`/notes/note/${props.slug}`"
                        class="text-base font-semibold text-pink-700 dark:text-pink-500 hover:text-pink-800 dark:hover:text-pink-600"
                    >
                        Read the note
                    </router-link>
                </div>
            </div>
        </div>
    </div>
</template>

// components/NoteCard.tsx
import type{ Writing } from "../types/writings";

const NoteCard = ({ note }: { note: Writing }) => {
    return (
        <div className="mt-1 pt-5 hover:cursor-pointer">
            <div className="items-center">
                <div className="col-span-2">
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                        <time dateTime={note.published}>
                            {new Date(
                                `${note.published}T12:00:00-07:00`,
                            ).toLocaleDateString(undefined, {
                                year: "numeric",
                                month: "long",
                                day: "numeric",
                            })}
                        </time>
                    </p>

                    <span className="mt-2 block">
                        <p className="text-xl font-semibold text-gray-800 dark:text-gray-200">
                            {note.title}
                        </p>
                        <p className="mt-2 text-base text-gray-500 dark:text-gray-400">
                            {note.description}
                        </p>
                    </span>

                    <div className="mt-3">
                        <span className="text-base font-semibold text-pink-700 dark:text-pink-500 hover:text-pink-800 dark:hover:text-pink-600">
                            Read the note
                        </span>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default NoteCard;
