// pages/programs.tsx
import Head from "next/head";
import Layout from "../components/Layout";
import Link from "next/link";
import ProgramCard from "../components/ProgramCard";
import { programs } from "../data/pages";
import type { NextPage } from "next";

const Programs: NextPage = () => {
    return (
        <Layout>
            <Head>
                <title>Programs | H. Kamran</title>
            </Head>

            <h1 className="text-3xl font-semibold">Programs</h1>
            <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                {programs.map((program, index) => (
                    <Link key={index} href={`/program/${program.id}`} passHref>
                        <a>
                            <ProgramCard program={program} />
                        </a>
                    </Link>
                ))}
            </div>
        </Layout>
    );
};

export default Programs;

// src/views/Programs.vue
<script setup lang="ts">
import MainLayout from "../components/MainLayout.vue";
import ProgramCard from "../components/ProgramCard.vue";
import programs from "../data/programs.json";

// console.debug(programs);
</script>

<template>
    <main-layout title="Programs" two-grid v-slot>
        <program-card
            v-for="program in programs"
            :key="program.id"
            :id="program.id"
            :name="program.name"
            :description="program.description"
        />
    </main-layout>
</template>
