// components/FinalGradeCalculatorProgram.tsx
import { useEffect, useState } from "react";
import feather from "feather-icons";
import InputField from "./InputField";
import { resizeIcon } from "@hkamran/utility-web";

const messages = (score: number): string => {
    if (score > 100) {
        return 'Impossible. But as Tommy Lasorda said, "The difference between the impossible and the possible lies in a man\'s determination."';
    } else if (score < 0) {
        return "Uhhh...yeah, go ahead and flunk the final, you should get the grade you want.";
    } else {
        return "Achievable. I have faith in you.";
    }
};

const FinalGradeCalculatorProgram = () => {
    const [currentGrade, setCurrentGrade] = useState<number | null>(null);
    const [gradeWanted, setGradeWanted] = useState<number | null>(null);
    const [finalWeight, setFinalWeight] = useState<number | null>(null);
    const [scoreNeeded, setScoreNeeded] = useState<string | null>(null);

    useEffect(() => {
        if (currentGrade && gradeWanted && finalWeight) {
            let score =
                (gradeWanted * 100 - currentGrade * (100 - finalWeight)) /
                finalWeight;

            setScoreNeeded(score.toFixed(2));
        }
    }, [currentGrade, gradeWanted, finalWeight]);

    return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-1">
            <InputField
                type="number"
                placeholder="Current Grade"
                label="Current Grade"
                value={currentGrade || 0}
                valueUpdate={(value) => setCurrentGrade(value as number)}
                svg={resizeIcon(feather.icons.percent.toSvg())}
            />

            <InputField
                type="number"
                placeholder="Grade Wanted"
                label="Grade Wanted"
                value={gradeWanted || 0}
                valueUpdate={(value) => setGradeWanted(value as number)}
                svg={resizeIcon(feather.icons.percent.toSvg())}
            />

            <InputField
                type="number"
                placeholder="Final Weight"
                label="Final Weight"
                value={finalWeight || 0}
                classes="md:col-span-2"
                valueUpdate={(value) => setFinalWeight(value as number)}
                svg={resizeIcon(feather.icons.percent.toSvg())}
            />

            <div className="md:col-span-2">
                <hr
                    className="mb-4"
                    style={{
                        border: 0,
                        height: "1px",
                        background: "#374151",
                    }}
                />

                <InputField
                    type="number"
                    placeholder="Score Needed"
                    label="Score Needed"
                    value={scoreNeeded || ""}
                    valueUpdate={(value) => {}}
                    svg={resizeIcon(feather.icons.percent.toSvg())}
                    disabled
                />

                <span>{scoreNeeded && messages(Number(scoreNeeded))}</span>
            </div>
        </div>
    );
};

export default FinalGradeCalculatorProgram;

// src/components/FinalGradeCalculatorProgram.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import _feather from "feather-icons";

import InputField from "../components/InputField.vue";

const currentGrade = ref<number | null>(null);
const gradeWanted = ref<number | null>(null);
const finalWeight = ref<number | null>(null);
const scoreNeeded = ref<string | null>(null);
const scoreNeededMessage = ref<string | null>(null);

watch(
    [currentGrade, gradeWanted, finalWeight],
    ([newCurrentGrade, newGradeWanted, newFinalWeight]) => {
        if (newCurrentGrade && newGradeWanted && newFinalWeight) {
            let score =
                (newGradeWanted * 100 -
                    newCurrentGrade * (100 - newFinalWeight)) /
                newFinalWeight;

            scoreNeeded.value = score.toFixed(2);
            scoreNeededMessage.value =
                score > 100
                    ? 'Impossible. But as Tommy Lasorda said, "The difference between the impossible and the possible lies in a man\'s determination."'
                    : score < 0
                    ? "Uhhh...yeah, go ahead and flunk the final, you should get the grade you want."
                    : "Achievable. I have faith in you.";
        }
    },
);

const feather = _feather;
</script>

<template>
    <div
        class="mt-7 grid sm:grid-cols-2 grid-cols-1 gap-x-8 gap-y-2 items-center"
    >
        <input-field
            v-model="currentGrade"
            class="col-span-2 sm:col-span-1"
            type="number"
            placeholder="Current Grade"
            :svg="feather.icons.percent.toSvg()"
            step="any"
        />
        <input-field
            v-model="gradeWanted"
            class="col-span-2 sm:col-span-1"
            type="number"
            placeholder="Grade Wanted"
            :svg="feather.icons.percent.toSvg()"
            step="any"
        />
        <input-field
            v-model="finalWeight"
            class="col-span-2"
            type="number"
            placeholder="Final Weight"
            :svg="feather.icons.percent.toSvg()"
            step="any"
        />

        <div class="col-span-2">
            <hr class="mb-4" />

            <input-field
                v-model="scoreNeeded"
                type="number"
                placeholder="Score Needed"
                :svg="feather.icons.percent.toSvg()"
                step="any"
                readonly
            />
            <span v-text="scoreNeededMessage" />
        </div>
    </div>
</template>
