// components/OverallGradeAfterFinalCalculatorProgram.tsx
import { useEffect, useState } from "react";
import feather from "feather-icons";
import InputField from "./InputField";
import { resizeIcon } from "@hkamran/utility-web";

const OverallGradeAfterFinalCalculatorProgram = () => {
    const [gradeBeforeFinal, setGradeBeforeFinal] = useState<number | null>(
        null,
    );
    const [finalScore, setFinalScore] = useState<number | null>(null);
    const [finalWeight, setFinalWeight] = useState<number | null>(null);
    const [gradeAfterFinal, setGradeAfterFinal] = useState<string | null>(null);

    useEffect(() => {
        if (gradeBeforeFinal && finalScore && finalWeight) {
            let finalWeightDecimal = finalWeight / 100;
            let score =
                ((1 - finalWeightDecimal) * (gradeBeforeFinal / 100) +
                    finalWeightDecimal * (finalScore / 100)) *
                100;

            setGradeAfterFinal(score.toFixed(2));
        }
    }, [gradeBeforeFinal, finalScore, finalWeight]);

    return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-1">
            <InputField
                type="number"
                placeholder="Grade Before Final"
                label="Grade Before Final"
                value={gradeBeforeFinal || undefined}
                valueUpdate={(value) => setGradeBeforeFinal(value as number)}
                svg={resizeIcon(feather.icons.percent.toSvg())}
            />

            <InputField
                type="number"
                placeholder="Final Score"
                label="Final Score"
                value={finalScore || undefined}
                valueUpdate={(value) => setFinalScore(value as number)}
                svg={resizeIcon(feather.icons.percent.toSvg())}
            />

            <InputField
                type="number"
                placeholder="Final Weight"
                label="Final Weight"
                value={finalWeight || undefined}
                classes="md:col-span-2"
                valueUpdate={(value) => setFinalWeight(value as number)}
                svg={resizeIcon(feather.icons.percent.toSvg())}
            />

            <div className="md:col-span-2">
                <hr
                    className="mb-4"
                    style={{
                        border: 0,
                        height: "1px",
                        background: "#374151",
                    }}
                />

                <InputField
                    type="number"
                    placeholder="Grade After Final"
                    label="Grade After Final"
                    value={gradeAfterFinal || ""}
                    valueUpdate={(value) => {}}
                    svg={resizeIcon(feather.icons.percent.toSvg())}
                    disabled
                />
            </div>
        </div>
    );
};

export default OverallGradeAfterFinalCalculatorProgram;

// src/components/OverallGradeAfterFinalCalculatorProgram.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import _feather from "feather-icons";

import InputField from "./InputField.vue";

const gradeBeforeFinal = ref<number | null>(null);
const finalScore = ref<number | null>(null);
const finalWeight = ref<number | null>(null);
const gradeAfterFinal = ref<string | null>(null);

watch(
    [gradeBeforeFinal, finalScore, finalWeight],
    ([newGradeBeforeFinal, newFinalScore, newFinalWeight]) => {
        if (newGradeBeforeFinal && newFinalScore && newFinalWeight) {
            let finalWeightDecimal = newFinalWeight / 100;

            gradeAfterFinal.value = (
                ((1 - finalWeightDecimal) * (newGradeBeforeFinal / 100) +
                    finalWeightDecimal * (newFinalScore / 100)) *
                100
            ).toFixed(2);
        }
    },
);

const feather = _feather;
</script>

<template>
    <div
        class="mt-7 grid sm:grid-cols-2 grid-cols-1 gap-x-8 gap-y-2 items-center"
    >
        <input-field
            class="col-span-2 sm:col-span-1"
            type="number"
            placeholder="Grade Before Final"
            :svg="feather.icons.percent.toSvg()"
            step="any"
            v-model="gradeBeforeFinal"
        />
        <input-field
            class="col-span-2 sm:col-span-1"
            type="number"
            placeholder="Final Score"
            :svg="feather.icons.percent.toSvg()"
            step="any"
            v-model="finalScore"
        />
        <input-field
            class="col-span-2"
            type="number"
            placeholder="Final Weight"
            :svg="feather.icons.percent.toSvg()"
            step="any"
            v-model="finalWeight"
        />

        <div class="col-span-2">
            <hr class="mb-4" />

            <input-field
                type="number"
                placeholder="Grade After Final"
                :svg="feather.icons.percent.toSvg()"
                step="any"
                v-model="gradeAfterFinal"
                readonly
            />
        </div>
    </div>
</template>
