// components/ProgramCard.tsx
import type { Page } from "../types/pages";

const ProgramCard = ({ program }: { program: Page }) => {
    return (
        <div
            className="w-full bg-hk-grey hover:bg-hk-grey-hover transition-colors duration-300 rounded-lg"
            aria-label={program.name}
        >
            <div className="w-full p-6 space-y-0.5">
                <span className="text-white text-md font-medium truncate">
                    {program.name}
                </span>
                <p className="text-gray-400 text-sm">
                    {program.description}
                </p>
            </div>
        </div>
    );
};

export default ProgramCard;

// src/components/ProgramCard.vue
<script setup lang="ts">
const props = defineProps<{
    name: string;
    description: string;
}>();
</script>

<template>
    <div class="w-full bg-white rounded-lg shadow">
        <div class="w-full flex items-center justify-between p-6 space-x-6">
            <div class="flex-1">
                <div class="flex items-center space-x-3">
                    <h3
                        class="text-gray-900 text-md font-medium truncate"
                        v-text="props.name"
                    />
                </div>
                <p
                    class="mt-1 text-gray-500 text-sm"
                    v-text="props.description"
                />
            </div>
        </div>
    </div>
</template>
